/**
 * Common configuration
 */

var infodisplayConfig = {
    CLOCK_UPDATE_TIMEOUT_MILLIS: 100,
    PAGE_RELOAD_INTERVAL_MILLIS: 1000*60*30,
    REITTIOPAS_REFRESH_TIMEOUT_MILLIS: 1000*10,
    WEATHER_REFRESH_TIMEOUT_MILLIS: 1000*60*5,
    TIME_LIMIT: 10,
    ARRIVAL_ITEMS: 4
};

